### ISSUE TITLE
Slash-ed branches cannot be found with Jenkins API

### ISSUE THREAD

**Issue by scaytrase** [mjdetullio/multi-branch-project-plugin#57] opened 2015-05-21 10:36 UTC
Given I run the following script at the Jenkins Script Console
```groovy
Jenkins.instance.getJobNames().each {
  name -> println name + " -> " + Jenkins.instance.getItemByFullName(name)
}

return
```

I'm expecting that every job name is mapped to Jenkins Item objects

But instead if the multibranch project has slash in it - it returns null. i.e.

```
  multibranch_test -> com.github.mjdetullio.jenkins.plugins.multibranch.FreeStyleMultiBranchProject@7a09bb6a[multibranch_test]
  multibranch_test/master -> hudson.model.FreeStyleProject@6c5b7159[multibranch_test/master]
  multibranch_test/release/1 -> null
```

The initial problem that lead me to this finding was that `MultiJob Plugin` Phase subjob is not displayed when job name contains second slash in it.

**Comment by mjdetullio** [comment] 2015-06-30 01:42
```getItemByFullName``` uses the slash as a separator token, making the assumption that between each slash is an item.  Jenkins does declare the slash as unsafe if I were to try creating a job through the UI, but it also doesn't allow characters needed for name encoding.

For this API to work properly I'd have to work on the option to replace branch slashes and other characters with an underscore or other user configurable character per #15

**Comment by mjdetullio** [comment] 2015-06-30 04:02
More or less a duplicate of #50

**Closed by mjdetullio** 2015-06-30 04:02 UTC
Labels: duplicate
