### ISSUE TITLE
Delete workspaces when branches are removed

### ISSUE THREAD

**Issue by marcrohlfs** [mjdetullio/multi-branch-project-plugin#52] opened 2015-04-29 13:36 UTC
When a branch is deleted from a repository, the branch is deleted from the project view but the workspaces for that branch remain in the file system. Currently there's no way to remove them but identifying obsolete workspace directories in the file system and delete them manually. Projects with many (feature) branches may end up occupying a huge amount of disk space. Workspace directories should rather be deleted when branches are deleted.

**Comment by mjdetullio** [comment] 2015-04-29 14:58
Related to (or duplicate of?) #32 

Are you witnessing this with the latest version of the plugin?  Is this occurring on the master or on slaves?

When any Jenkins project is deleted, there isn't a mechanism for deleting the workspace if it is outside the project's main configuration directory on the master.  The same goes for these projects.

Last time I tried to reproduce was in 0.2.x of the plugin and didn't have the issue.

**Comment by marcrohlfs** [comment] 2015-05-06 09:59
Hi Matt, sorry for the late reply. We are using plugin version 0.2.2 and (still) facing this problem. I'd like to do some further analysis on this, but I unfortunately don't find time for this this week. Just some ideas:

* Could it be related to the core version? We're currently running 1.580.3. Don't think this should be a problem.
* We're delegating the builds to a slave. Hence the workspaces that are not cleaned up are all on a slave, no on the Jenkins master. I rather think this could be the problem.

Can You confirm/negate any of my assumptions?

Kind regards, Marc

**Comment by KenHundley** [comment] 2015-05-06 13:42
I'm experiencing the same issue as well. Currently my Jenkins is installed locally as I'm testing a new setup, so there are no additional nodes.

Here is some of the information about my setup:
Jenkins version: 1.611
Default Workspace Root Directory: e:/Jenkins/${ITEM_FULL_NAME}/workspace
Default Build Record Root Directory: e:/Jenkins/${ITEM_FULL_NAME}/builds
Plugin version: 0.2.2

**Comment by morlajb** [comment] 2015-06-29 08:29
I solve this problem with using the "delete workspace when build is done" from http://wiki.jenkins-ci.org/display/JENKINS/Workspace+Cleanup+Plugin

**Comment by marcrohlfs** [comment] 2015-06-29 08:56
We've also configured this workaround. But it's not more than just a workaround. For problem analysis it's useful to keep at least failed or even unstable builds. In some (rare) cases it's even useful to have a look at the workspace of a successful build.

**Comment by mjdetullio** [comment] 2015-06-30 02:06
Jenkins does not provide a way to clean up workspaces of deleted jobs.  This will only happen by coincidence if the workspace is on the master at a location like ```${ITEM_ROOTDIR}/workspace``` and no processes have a lock on the files.

Going to close as a duplicate.

**Closed by mjdetullio** 2015-06-30 02:06 UTC
Labels: duplicate
