### ISSUE TITLE
Fix /cc.xml

### ISSUE THREAD

**Issue by johnhamelink** [mjdetullio/multi-branch-project-plugin#102] opened 2015-09-23 12:01 UTC
Hey there,

I've been using multi-branch-project-plugin for a short while now - it really is the handiest thing ever!

One bug I've noticed is that the `/cc.xml` endpoint which can be used to monitor builds has not been updated to include the job status of each branch:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Projects>
   <Project webUrl="http://ci.example.com/jenkins/job/API/" name="API" lastBuildLabel="8" lastBuildTime="2015-09-23T11:50:56Z" lastBuildStatus="Unknown" activity="Sleeping" />
   <Project webUrl="http://ci.example.com/jenkins/job/Backup%20Jenkins%20to%20S3/" name="Backup Jenkins to S3" lastBuildLabel="41" lastBuildTime="2015-09-22T22:11:00Z" lastBuildStatus="Success" activity="Sleeping" />
   <Project webUrl="http://ci.example.com/jenkins/job/Deploy_API/" name="Deploy API" lastBuildLabel="177" lastBuildTime="2015-09-23T11:39:52Z" lastBuildStatus="Success" activity="Sleeping" />
</Projects>
```

As you can see the `Backup Jenkins to S3` and `Deploy API` builds show correctly. The multi-branch job `API` has a lastBuildStatus of `Unknown`.

I think the correct behaviour here would be to show a project for each branch associated with the `API` job, but not the `API` job itself.

**Comment by mjdetullio** [comment] 2015-09-24 21:01
Duplicate of #81

**Closed by mjdetullio** 2015-09-24 21:01 UTC
Labels: jenkins-core, wontfix
